name: storage
description: Storage for dart projects.
version: 0.0.0+1

environment:
  sdk: ">=2.3.1 <3.0.0"


dependencies:
  uuid: ^2.0.2
  logging: ^0.11.3+2
  graphql_parser: ^1.1.3
  graphql_schema: ^1.0.4

dev_dependencies:
  test: ^1.6.4
